version: '3.8'

services:
  # 1. Production MySQL Storage Layer
  ecommerce-db:
    image: mysql:8.0
    container_name: ecommerce-db
    restart: unless-stopped
    ports:
      - "3307:3306" # Your app on localhost will connect to port 3311
    environment:
      - MYSQL_ROOT_PASSWORD=prod_root_secure_pass_99
      - MYSQL_USER=appuser
      - MYSQL_PASSWORD=apppassword
      - MYSQL_DATABASE=ecommerce_db
    volumes:
      - ecommerce_data:/var/lib/mysql
      - ./infrastructure/mysql_config:/etc/mysql/conf.d # Keeps your custom configuration organized
    command: --default-authentication-plugin=mysql_native_password --binlog-format=ROW --binlog-row-image=FULL
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pprod_root_secure_pass_99"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 60s
    networks:
      - eshop-microservice-network

  # User Production MySQL Storage Layer
  # user-db:
  #   image: mysql:8.0
  #   container_name: user-db
  #   restart: unless-stopped
  #   ports:
  #     - "3308:3306" # Your app on localhost will connect to port 3311
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=prod_root_secure_pass_99
  #     - MYSQL_USER=appuser
  #     - MYSQL_PASSWORD=apppassword
  #     - MYSQL_DATABASE=user_db
  #   volumes:
  #     - user_data:/var/lib/mysql
  #     - ./infrastructure/mysql_config:/etc/mysql/conf.d # Keeps your custom configuration organized
  #   command: --default-authentication-plugin=mysql_native_password --binlog-format=ROW --binlog-row-image=FULL
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pprod_root_secure_pass_99"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10
  #     start_period: 60s
  #   networks:
  #     - eshop-microservice-network

  # # Inventory Production MySQL Storage Layer
  # inventory-db:
  #   image: mysql:8.0
  #   container_name: inventory-db
  #   restart: unless-stopped
  #   ports:
  #     - "3309:3306" # Your app on localhost will connect to port 3311
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=prod_root_secure_pass_99
  #     - MYSQL_USER=appuser
  #     - MYSQL_PASSWORD=apppassword
  #     - MYSQL_DATABASE=inventory_db
  #   volumes:
  #     - inventory_data:/var/lib/mysql
  #     - ./infrastructure/mysql_config:/etc/mysql/conf.d # Keeps your custom configuration organized
  #   command: --default-authentication-plugin=mysql_native_password --binlog-format=ROW --binlog-row-image=FULL
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pprod_root_secure_pass_99"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10
  #     start_period: 60s
  #   networks:
  #     - eshop-microservice-network

  # # Order Production MySQL Storage Layer
  # order-db:
  #   image: mysql:8.0
  #   container_name: order-db
  #   restart: unless-stopped
  #   ports:
  #     - "3310:3306" # Your app on localhost will connect to port 3311
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=prod_root_secure_pass_99
  #     - MYSQL_USER=appuser
  #     - MYSQL_PASSWORD=apppassword
  #     - MYSQL_DATABASE=order_db
  #   volumes:
  #     - order_data:/var/lib/mysql
  #     - ./infrastructure/mysql_config:/etc/mysql/conf.d # Keeps your custom configuration organized
  #   command: --default-authentication-plugin=mysql_native_password --binlog-format=ROW --binlog-row-image=FULL
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pprod_root_secure_pass_99"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10
  #     start_period: 60s
  #   networks:
  #     - eshop-microservice-network

  # # Order Production MySQL Storage Layer
  # payment-db:
  #   image: mysql:8.0
  #   container_name: payment-db
  #   restart: unless-stopped
  #   ports:
  #     - "3311:3306" # Your app on localhost will connect to port 3311
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=prod_root_secure_pass_99
  #     - MYSQL_USER=appuser
  #     - MYSQL_PASSWORD=apppassword
  #     - MYSQL_DATABASE=payment_db
  #   volumes:
  #     - payment_data:/var/lib/mysql
  #     - ./infrastructure/mysql_config:/etc/mysql/conf.d # Keeps your custom configuration organized
  #   command: --default-authentication-plugin=mysql_native_password --binlog-format=ROW --binlog-row-image=FULL
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pprod_root_secure_pass_99"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10
  #     start_period: 60s
  #   networks:
  #     - eshop-microservice-network

  # # Order Production MySQL Storage Layer
  # notification-db:
  #   image: mysql:8.0
  #   container_name: notification-db
  #   restart: unless-stopped
  #   ports:
  #     - "3312:3306" # Your app on localhost will connect to port 3311
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=prod_root_secure_pass_99
  #     - MYSQL_USER=appuser
  #     - MYSQL_PASSWORD=apppassword
  #     - MYSQL_DATABASE=notification_db
  #   volumes:
  #     - notification_data:/var/lib/mysql
  #     - ./infrastructure/mysql_config:/etc/mysql/conf.d # Keeps your custom configuration organized
  #   command: --default-authentication-plugin=mysql_native_password --binlog-format=ROW --binlog-row-image=FULL
  #   healthcheck:
  #     test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-pprod_root_secure_pass_99"]
  #     interval: 10s
  #     timeout: 5s
  #     retries: 10
  #     start_period: 60s
  #   networks:
  #     - eshop-microservice-network

  # 2. Apache Kafka Controller/Broker (KRaft Mode)
  kafka:
    image: confluentinc/cp-kafka:7.6.0
    container_name: kafka-kraft-broker
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_NODE_ID: 1
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:29093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_LISTENERS: 'PLAINTEXT://0.0.0.0:29092,CONTROLLER://0.0.0.0:29093,PLAINTEXT_HOST://0.0.0.0:9092'
      KAFKA_ADVERTISED_LISTENERS: 'PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'PLAINTEXT'
      CLUSTER_ID: 'MkU3OEVBNTcwNTJENDM2Qk'
      KAFKA_NUM_PARTITIONS: 16
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_LOG_RETENTION_HOURS: 72
      KAFKA_LOG_SEGMENT_BYTES: 1073741824
    volumes:
      - kafka_production_data:/var/lib/kafka/data
    networks:
      - eshop-microservice-network

  #3. Isolated Kafka UI Management Dashboard
  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    container_name: kafka-management-ui
    restart: unless-stopped
    ports:
      - "8080:8080"
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: 'false'
      KAFKA_CLUSTERS_0_NAME: production-kraft-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:29092
      KAFKA_CLUSTERS_0_SCHEMAREGISTRY: http://schema-registry:8081
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_NAME: debezium-cluster
      KAFKA_CLUSTERS_0_KAFKACONNECT_0_ADDRESS: http://debezium-connect:8083
    networks:
      - eshop-microservice-network

  #4. Redis Cache
  redis:
    image: redis:7.4-alpine
    container_name: redis-cache
    restart: unless-stopped

    ports:
      - "6379:6379"

    command:
      [
        "redis-server",
        "/usr/local/etc/redis/redis.conf"
      ]

    volumes:
      - redis_data:/data
      - ./infrastructure/redis/redis.conf:/usr/local/etc/redis/redis.conf:ro

    healthcheck:
      test: ["CMD", "redis-cli", "-a", "Redis@123", "PING"]
      interval: 15s
      timeout: 5s
      retries: 5
      start_period: 20s

    ulimits:
      memlock:
        soft: -1
        hard: -1

    networks:
      - eshop-microservice-network

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.1
    container_name: elasticsearch
    restart: unless-stopped
    ports:
      - "29200:9200"
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false # Disabled for easy local development
      - xpack.security.enrollment.enabled=false
      - ES_JAVA_OPTS=-Xms1g -Xmx1g
    volumes:
      - es_data:/usr/share/elasticsearch/data
    networks:
      - eshop-microservice-network

  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.1
    container_name: kibana-dashboard
    restart: unless-stopped
    ports:
      - "5601:5601"
    depends_on:
      elasticsearch:
        condition: service_started
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - XPACK_SECURITY_ENABLED=false
    networks:
      - eshop-microservice-network

volumes:
  # product_catalog_data:
  # user_data:
  # inventory_data:
  # order_data:
  # payment_data:
  # notification_data:
  ecommerce_data:
  kafka_production_data:
  redis_data:
  es_data:

networks:
  eshop-microservice-network:
    driver: bridge