
@baseUrl = http://localhost:8081/api/v1/products


### 1. (Create Product)
POST {{baseUrl}}
Content-Type: application/json

{
  "name": "Nokia Keypad",
  "sku": "NOKIA-N1000",
  "price": 50.00,
  "categoryId": 107,
  "active": true
}

### 2. (Get Product)
GET {{baseUrl}}/2
Content-Type: application/json