@host=http://localhost:8083
@baseUrl={{host}}/api/v1/carts

############################################################
# Add Item 1
############################################################

POST {{baseUrl}}/items
Content-Type: application/json

{
  "userId": 1,
  "productId": 101,
  "quantity": 2,
  "unitPrice": 999.99
}

###

############################################################
# Add Item 2
############################################################

POST {{baseUrl}}/items
Content-Type: application/json

{
  "userId": 1,
  "productId": 102,
  "quantity": 1,
  "unitPrice": 1499.99
}

###

############################################################
# Add Item 3
############################################################

POST {{baseUrl}}/items
Content-Type: application/json

{
  "userId": 1,
  "productId": 103,
  "quantity": 3,
  "unitPrice": 199.99
}

###

############################################################
# Add Item for another User
############################################################

POST {{baseUrl}}/items
Content-Type: application/json

{
  "userId": 2,
  "productId": 101,
  "quantity": 1,
  "unitPrice": 999.99
}

###

############################################################
# Get Cart
############################################################

GET {{baseUrl}}/1

###

############################################################
# Get Cart with Discount
############################################################

GET {{baseUrl}}/1?discountPercentage=10

###

############################################################
# Update Quantity
############################################################

PUT {{baseUrl}}/1/items/101?quantity=5

###

############################################################
# Get Cart Again
############################################################

GET {{baseUrl}}/1

###

############################################################
# Remove Product
############################################################

DELETE {{baseUrl}}/1/items/102

###

############################################################
# Get Cart Again
############################################################

GET {{baseUrl}}/1

###

############################################################
# Clear Cart
############################################################

DELETE {{baseUrl}}/1

###

############################################################
# Verify Cart Empty
############################################################

GET {{baseUrl}}/1