server:
  port: 8000

spring:
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        options:
          model: qwen2.5:7b
          temperature: 0.2
    mcp:
      client:
        enabled: true
        name: agentic-ai-client
        version: 1.0.0
        type: SYNC # Set to SYNC so Spring creates SyncMcpToolCallbackProvider
        sse:
          connections:
            # Connection 1: Order Microservice
            order-service:
              url: http://localhost:8081
              sse-endpoint: /mcp/sse
            # Connection 2: Inventory Microservice
            inventory-service:
              url: http://localhost:8082
              sse-endpoint: /mcp/sse
            # Connection 3: Payment Microservice
            payment-service:
              url: http://localhost:8083
              sse-endpoint: /mcp/sse
            # Connection 4: Product Microservice
            product-service:
              url: http://localhost:8084
              sse-endpoint: /mcp/sse